name: Release Drafter
on:
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Draft a release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}